fc_cnn_wm:
  model: 
    model_name: "model.pth"
    architecture: "resnet34" 
    turn_off_batch_norm: false
  wm_settings:
    wm_type: "ood_abstract" 
    wm_classes: [0]
    wm_th: 80 
    batch_size: 32
    optimizer: 'sgd' 
    lr: 0.001
    momentum: 0.9 
    max_epochs: 100 
  data: 
    dataset_name: null 
    dataset_folder: null
    data_extensions: null
    trigger_set_size: 100
    image_size: 
      height: 224
      width: 224
    num_channels: 3
    num_classes: 10
    mean: null
    std: null